# Generated by Django 4.2.7 on 2023-11-22 08:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("chat", "0001_initial"),
    ]

    operations = [
        migrations.RenameField(
            model_name="chatserver",
            old_name="online",
            new_name="users",
        ),
    ]
