# Generated by Django 4.2.7 on 2023-11-30 14:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("chat", "0005_chatserver_admins"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="chatserver",
            name="admins",
        ),
        migrations.RemoveField(
            model_name="room",
            name="adminsOnly",
        ),
    ]
