# Generated by Django 4.2.7 on 2023-11-30 14:04

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("chat", "0006_remove_chatserver_admins_remove_room_adminsonly"),
    ]

    operations = [
        migrations.AddField(
            model_name="room",
            name="room_admins",
            field=models.ManyToManyField(
                blank=True, related_name="room_admins", to=settings.AUTH_USER_MODEL
            ),
        ),
    ]
