# Generated by Django 4.2.7 on 2023-11-30 14:59

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("chat", "0007_room_room_admins"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="chatserver",
            name="users",
        ),
        migrations.AddField(
            model_name="chatserver",
            name="members",
            field=models.ManyToManyField(
                blank=True, related_name="server_members", to=settings.AUTH_USER_MODEL
            ),
        ),
    ]
