# Generated by Django 4.2.7 on 2023-11-30 15:15

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("chat", "0008_remove_chatserver_users_chatserver_members"),
    ]

    operations = [
        migrations.AddField(
            model_name="room",
            name="creator",
            field=models.ForeignKey(
                default=1,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="room_creator",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AlterField(
            model_name="room",
            name="online",
            field=models.ManyToManyField(
                blank=True, related_name="online_users", to=settings.AUTH_USER_MODEL
            ),
        ),
    ]
