# Generated by Django 4.2.7 on 2023-11-30 15:16

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("chat", "0009_room_creator_alter_room_online"),
    ]

    operations = [
        migrations.AlterField(
            model_name="room",
            name="creator",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="room_creator",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
